#!/bin/bash

WORK_DIR=$(pwd)

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

mkdir -p ~/.local/bin
mkdir -p ~/.local/nvim
cd ~/.local/nvim
wget https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage && \
chmod u+x nvim.appimage && \
./nvim.appimage --appimage-extract
ln -sf $(pwd)/squashfs-root/usr/bin/nvim ~/.local/bin/nvim

mkdir -p ~/.config
rm -rf ~/.config/nvim
cp -r ${WORK_DIR}/.devcontainer/config/nvim ~/.config/nvim
